export const getPOIEmoji = (cls?: string, sub?: string, name?: string): string => {
  const emojiMap: Record<string, string> = {
    peak: '🔺',
    water: '💧',
    lake: '💧',
    campsite: '⛺',
    alpine_hut: '🛖',
    viewpoint: '🔭',
    historic: '🏛️',
    restaurant: '🍴',
    cafe: '☕',
    parking: '🅿️',
    information: 'ℹ️',
    shelter: '🛖',
    bus_stop: '🚌',
    station: '🚉',
    bar: '🍻',
    supermarket: '🛒',
    bakery: '🥖',
    fast_food: '🍔',
    hospital: '🏥',
    pharmacy: '💊',
    police: '🚓',
    toilets: '🚻',
    waste_basket: '🗑️',
    bench: '🪑',
    atm: '🏧',
    bank: '🏦',
    post_office: '📮',
    school: '🏫',
    swimming_pool: '🏊',
    rock: '🪨',
    natural: '🍃',
    stone: '🪨',
    saddle: '⛰️',
    place_of_worship: '⛪',
    church: '⛪',
    mosque: '🕌',
    synagogue: '🕍',
    hindu_temple: '🛕'
  };

  if ((cls === 'peak' || sub === 'peak') && (!name || name.trim() === '')) return emojiMap['rock'];
  return (sub && emojiMap[sub]) || (cls && emojiMap[cls]) || '📍';
};
